# Generated by Django 5.2.7 on 2026-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_downloads_material_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
