# Generated by Django 6.0.3 on 2026-04-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_material_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
